Repository chaehoonii/IsTudy, pull requests merged in 2022-05, with the labels that each got.

#3 TOP BOTTOM css적용
  istudy/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/css/inc/top.css
Labels: enhancement

#5 top 타이틀 수정
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
Labels: enhancement

#7 [FEAT] 스터디 등록페이지 jsp 생성 및 PR템플릿 생성 - close #6
  .github/ISSUE_TEMPLATE/issue_BUG.md
  .github/ISSUE_TEMPLATE/issue_FEAT.md
  .github/PULL_REQUEST_TEMPLATE.md
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_1.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_2.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_3.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_4.jsp
Labels: documentation, enhancement

#12 로그인 페이지 추가
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/com/hot6/project/dao/UserDAO.class
  istudy/bin/main/com/hot6/project/service/UserService.class
  istudy/bin/main/com/hot6/project/service/UserServiceImpl.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/UserDAO.java
  istudy/src/main/java/com/hot6/project/service/UserService.java
  istudy/src/main/java/com/hot6/project/service/UserServiceImpl.java
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/images/id.png
  istudy/src/main/webapp/images/password.png
Labels: enhancement

#19 [PULL]
  istudy/bin/main/application.yml
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/com/hot6/project/dao/UserDAO.class
  istudy/bin/main/com/hot6/project/service/UserService.class
  istudy/bin/main/com/hot6/project/service/UserServiceImpl.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/build.gradle
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/UserDAO.java
  istudy/src/main/java/com/hot6/project/service/UserService.java
  istudy/src/main/java/com/hot6/project/service/UserServiceImpl.java
  istudy/src/main/resources/application.yml
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/users/idSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/WEB-INF/views/users/pwdSearch.jsp
  istudy/src/main/webapp/images/email.png
  istudy/src/main/webapp/images/id.png
  istudy/src/main/webapp/images/password.png
  istudy/src/main/webapp/images/phone.png
  istudy/src/main/webapp/images/user.png
Labels: documentation

#20 로그인 페이지 수정, 아이디 비밀번호 페이지 추가
  .github/ISSUE_TEMPLATE/issue_BUG.md
  .github/ISSUE_TEMPLATE/issue_FEAT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  istudy/bin/main/application.yml
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/com/hot6/project/dao/UserDAO.class
  istudy/bin/main/com/hot6/project/service/UserService.class
  istudy/bin/main/com/hot6/project/service/UserServiceImpl.class
  istudy/bin/main/com/hot6/project/vo/UserVO.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/build.gradle
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/UserDAO.java
  istudy/src/main/java/com/hot6/project/service/UserService.java
  istudy/src/main/java/com/hot6/project/service/UserServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/java/com/hot6/project/vo/UserVO.java
  istudy/src/main/resources/application.yml
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_1.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_2.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_3.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_4.jsp
  istudy/src/main/webapp/WEB-INF/views/users/idSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/WEB-INF/views/users/pwdSearch.jsp
  istudy/src/main/webapp/images/email.png
  istudy/src/main/webapp/images/id.png
  istudy/src/main/webapp/images/password.png
  istudy/src/main/webapp/images/phone.png
  istudy/src/main/webapp/images/user.png
Labels: enhancement

#21 스터디 등록 페이지 비동기식 페이지 전환 수정
  .github/ISSUE_TEMPLATE/issue_BUG.md
  .github/ISSUE_TEMPLATE/issue_FEAT.md
  .github/PULL_REQUEST_TEMPLATE.md
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/src/main/java/com/hot6/project/controller/StudyRegisterController.java
  istudy/src/main/java/com/hot6/project/dao/StudyRegisterDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyRegisterService.java
  istudy/src/main/java/com/hot6/project/service/StudyRegisterServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/StudyRegisterVO.java
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_0.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_1.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_2.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_3.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_4.jsp
  istudy/src/main/webapp/css/studyregister/studyregister.css
  istudy/src/main/webapp/js/studyregister/studyregisterForm.js
Labels: enhancement

#24 StudyRegisterVO 롬복 삭제 및 gitignore 경로 수정
  istudy/.gitignore
  istudy/README.md
  istudy/src/main/java/com/hot6/project/vo/StudyRegisterVO.java
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_0.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_2.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_3.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_4.jsp
  istudy/src/main/webapp/css/studyregister/studyregister.css
Labels: bug

#25 top bottom home 수정
  .gitignore
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/css/home.css
  istudy/src/main/webapp/css/home/home.css
  istudy/src/main/webapp/css/home/owl.carousel.css
  istudy/src/main/webapp/css/inc/bottom.css
  istudy/src/main/webapp/css/inc/top.css
  istudy/src/main/webapp/js/home/home.js
  istudy/src/main/webapp/js/home/owl.carousel.js
Labels: enhancement

#29 회원가입 페이지 구현
  istudy/bin/main/application.yml
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/com/hot6/project/dao/UserDAO.class
  istudy/bin/main/com/hot6/project/service/UserService.class
  istudy/bin/main/com/hot6/project/service/UserServiceImpl.class
  istudy/bin/main/com/hot6/project/vo/UserVO.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/build.gradle
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/UserDAO.java
  istudy/src/main/java/com/hot6/project/service/UserService.java
  istudy/src/main/java/com/hot6/project/service/UserServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/UserVO.java
  istudy/src/main/resources/application.yml
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/users/joinResult.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userForm.jsp
  istudy/src/main/webapp/css/users/userEdit.css
  istudy/src/main/webapp/css/users/userForm.css
  istudy/src/main/webapp/js/users/userEdit.js
  istudy/src/main/webapp/js/users/userForm.js
Labels: enhancement

#30 Feat/mypage dohyeon
  istudy/bin/main/application.yml
  istudy/bin/main/mapper/userMapper.xml
  istudy/build.gradle
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDAO.java
  istudy/src/main/java/com/hot6/project/dao/UserDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyService.java
  istudy/src/main/java/com/hot6/project/service/StudyServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/UserService.java
  istudy/src/main/java/com/hot6/project/service/UserServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/UserVO.java
  istudy/src/main/resources/application.yml
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/users/idSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/users/pwdSearch.jsp
  istudy/src/main/webapp/images/login_icon/email.png
  istudy/src/main/webapp/images/login_icon/password.png
  istudy/src/main/webapp/images/login_icon/phone.png
  istudy/src/main/webapp/images/login_icon/user.png
  istudy/src/main/webapp/images/mypage_img/exstudy1.jpg
  istudy/src/main/webapp/images/mypage_img/exstudy2.jpg
  istudy/src/main/webapp/images/mypage_img/exstudy3.jpg
Labels: enhancement

#32 [FEAT] 메인페이지 - 스터디 추천(언어타입, 태그 여러개 넣기)
  istudy/bin/main/com/hot6/project/HomeController.class
  istudy/bin/main/com/hot6/project/dao/StudyDAO.class
  istudy/bin/main/com/hot6/project/service/StudyService.class
  istudy/bin/main/com/hot6/project/service/StudyServiceImpl.class
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/bin/main/mapper/studyMapper.xml
  istudy/src/main/java/com/hot6/project/HomeController.java
  istudy/src/main/java/com/hot6/project/controller/StudyController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyService.java
  istudy/src/main/java/com/hot6/project/service/StudyServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/study/calendar/calendarList.jsp
  istudy/src/main/webapp/css/study/studyCalendar.css
Labels: enhancement

#34 [DOCS][STYLE] DB수정, css수정
  istudy/bin/main/mapper/studyMapper.xml
  istudy/src/main/java/com/hot6/project/vo/BoardVO.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/qnaMapper.xml
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/study/calendar/calendarList.jsp
  istudy/src/main/webapp/css/home/home.css
  istudy/src/main/webapp/js/study/calendar.js
Labels: documentation

#35 [BUG] web.xml 삭제
  istudy/src/main/webapp/WEB-INF/web.xml
Labels: bug

#36 [DB] 수정된 모델링 파일, 초기값
  DB/DB 초기값.sql
  DB/IsTudy_project model.mwb
Labels: enhancement

#37 [DB] select_reply 테이블 추가(reply_num, board_num(PK)) - 채택된 답변 저장
  DB/DB 초기값.sql
  DB/IsTudy_project model.mwb
Labels: enhancement

#40 마이페이지 스터디 관리, 글 관리 DB 연결 완료
  istudy/bin/main/mapper/studyMapper.xml
  istudy/bin/main/mapper/userMapper.xml
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/dao/MypageDAO.java
  istudy/src/main/java/com/hot6/project/dao/StudyDAO.java
  istudy/src/main/java/com/hot6/project/service/MypageService.java
  istudy/src/main/java/com/hot6/project/service/MypageServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyService.java
  istudy/src/main/java/com/hot6/project/service/StudyServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/BoardVO.java
  istudy/src/main/resources/mapper/mypageMapper.xml
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
Labels: enhancement

#44 Feat/studyroom chaehoon
  istudy/src/main/java/com/hot6/project/controller/StudyRegisterController.java
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_0.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_1.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_2.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_3.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_4.jsp
  istudy/src/main/webapp/css/studyregister/studyregister.css
  istudy/src/main/webapp/images/studyregister/algorithm.png
  istudy/src/main/webapp/images/studyregister/backend.png
  istudy/src/main/webapp/images/studyregister/english.png
  istudy/src/main/webapp/images/studyregister/frontend.png
  istudy/src/main/webapp/images/studyregister/mentor.png
  istudy/src/main/webapp/images/studyregister/project.png
  istudy/src/main/webapp/images/studyregister/user.png
  istudy/src/main/webapp/js/studyregister/imageUpload.js
Labels: enhancement

#45 회원가입 수정 및 회원정보 수정
  istudy/bin/main/application.yml
  istudy/bin/main/com/hot6/project/dao/UserDAO.class
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/bin/main/mapper/studyMapper.xml
  istudy/bin/main/mapper/userMapper.xml
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/controller/StudyController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/UserDAO.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/application.yml
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userEdit.jsp
  istudy/src/main/webapp/WEB-INF/web.xml
  istudy/src/main/webapp/css/users/userEdit.css
  istudy/src/main/webapp/js/users/userEdit.js
  istudy/src/main/webapp/js/users/userForm.js
Labels: enhancement

#46 스터디 정보 페이지
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/java/com/hot6/project/dao/StudyInfoDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoService.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/PagingVO.java
  istudy/src/main/java/com/hot6/project/vo/StudyInfoVO.java
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyInfo.jsp
  istudy/src/main/webapp/images/study_default.jpg
Labels: enhancement

#47 home css, js 수정
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/bin/main/mybatis-config.xml
  istudy/src/main/java/com/hot6/project/controller/NoticeController.java
  istudy/src/main/java/com/hot6/project/dao/NoticeDAO.java
  istudy/src/main/java/com/hot6/project/service/NoticeService.java
  istudy/src/main/java/com/hot6/project/service/NoticeServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/BoardVO.java
  istudy/src/main/resources/mapper/NoticeMapper.xml
  istudy/src/main/resources/mybatis-config.xml
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/notice/noticeList.jsp
  istudy/src/main/webapp/css/home/home.css
  istudy/src/main/webapp/css/notice/noticeList.css
  istudy/src/main/webapp/js/home/home.js
  istudy/src/main/webapp/js/notice/noticeList.js
Labels: enhancement

#48 HOME 오류 수정
  istudy/bin/main/mapper/studyMapper.xml
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
Labels: enhancement

#49 <div sytle="clear:both"></div> 추가
  istudy/src/main/java/com/hot6/project/controller/StudyRegisterController.java
  istudy/src/main/java/com/hot6/project/vo/StudyRegisterVO.java
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_0.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_2.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_3.jsp
  istudy/src/main/webapp/css/studyregister/studyregister.css
Labels: enhancement

#50 스터디 정보 페이지 URL 주소 변경
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/java/com/hot6/project/dao/StudyInfoDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoService.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoServiceImpl.java
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
Labels: documentation

#51 사이드바 width 퍼센트 변경
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/css/inc/top.css
Labels: enhancement

#53 메인 사이드바 / qna 댓글
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/QnaDAO.java
  istudy/src/main/java/com/hot6/project/service/QnaService.java
  istudy/src/main/java/com/hot6/project/service/QnaServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/BoardVO.java
  istudy/src/main/resources/mapper/qnaMapper.xml
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/css/inc/top.css
  istudy/src/main/webapp/css/qna/qnaView.css
  istudy/src/main/webapp/css/study/studyCalendar.css
Labels: enhancement

#54 로그인, 아이디 찾기, 비밀번호 찾기 페이지 수정 및 마이페이지 수정
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/dao/MypageDAO.java
  istudy/src/main/java/com/hot6/project/service/MypageService.java
  istudy/src/main/java/com/hot6/project/service/MypageServiceImpl.java
  istudy/src/main/resources/mapper/mypageMapper.xml
  istudy/src/main/webapp/WEB-INF/views/users/idSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/users/pwdSearch.jsp
Labels: enhancement

#55 - QnA 댓글 채택, 채택 취소 기능 - 댓글 삭제 기능 - 글 삭제 기능 - 사이트아이콘 등록
  istudy/bin/main/mybatis-config.xml
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/BoardDAO.java
  istudy/src/main/java/com/hot6/project/dao/QnaDAO.java
  istudy/src/main/java/com/hot6/project/service/BoardService.java
  istudy/src/main/java/com/hot6/project/service/BoardServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/QnaService.java
  istudy/src/main/java/com/hot6/project/service/QnaServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/BoardVO.java
  istudy/src/main/resources/mapper/boardMapper.xml
  istudy/src/main/resources/mapper/qnaMapper.xml
  istudy/src/main/resources/mybatis-config.xml
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/css/qna/qnaView.css
  istudy/src/main/webapp/images/lamp02.png
  istudy/src/main/webapp/upload/qna/1651911713707.png
Labels: enhancement

#56 게시글 등록, 삭제 공통 메소드
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/BoardDAO.java
  istudy/src/main/java/com/hot6/project/dao/QnaDAO.java
  istudy/src/main/java/com/hot6/project/service/BoardService.java
  istudy/src/main/java/com/hot6/project/service/BoardServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/QnaService.java
  istudy/src/main/java/com/hot6/project/service/QnaServiceImpl.java
  istudy/src/main/resources/mapper/boardMapper.xml
  istudy/src/main/resources/mapper/qnaMapper.xml
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaWrite.jsp
  istudy/src/main/webapp/css/qna/qnaView.css
Labels: enhancement

#58 댓글 리스트 공통 메소드
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/BoardDAO.java
  istudy/src/main/java/com/hot6/project/dao/QnaDAO.java
  istudy/src/main/java/com/hot6/project/service/BoardService.java
  istudy/src/main/java/com/hot6/project/service/BoardServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/QnaService.java
  istudy/src/main/java/com/hot6/project/service/QnaServiceImpl.java
  istudy/src/main/resources/mapper/boardMapper.xml
  istudy/src/main/resources/mapper/qnaMapper.xml
  istudy/src/main/webapp/WEB-INF/views/qna/qnaList.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
Labels: enhancement

#61 회원 관리 페이지 생성
  istudy/src/main/java/com/hot6/project/controller/AdminUserController.java
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/dao/AdminUserDAO.java
  istudy/src/main/java/com/hot6/project/service/AdminUserService.java
  istudy/src/main/java/com/hot6/project/service/AdminUserServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/MypageService.java
  istudy/src/main/java/com/hot6/project/service/MypageServiceImpl.java
  istudy/src/main/resources/mapper/adminUserMapper.xml
  istudy/src/main/resources/mapper/mypageMapper.xml
  istudy/src/main/webapp/WEB-INF/views/admin/users.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
  istudy/src/main/webapp/images/admin_img/search.png
Labels: enhancement

#64 [FEAT] 일정 drag&drop 사용한 수정 기능
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/com/hot6/project/dao/StudyDAO.class
  istudy/bin/main/com/hot6/project/service/StudyService.class
  istudy/bin/main/com/hot6/project/service/StudyServiceImpl.class
  istudy/bin/main/mapper/studyMapper.xml
  istudy/bin/main/mybatis-config.xml
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/CalendarController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/CalendarDAO.java
  istudy/src/main/java/com/hot6/project/dao/StudyDAO.java
  istudy/src/main/java/com/hot6/project/service/CalendarService.java
  istudy/src/main/java/com/hot6/project/service/CalendarServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/JobServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyService.java
  istudy/src/main/java/com/hot6/project/service/StudyServiceImpl.java
  istudy/src/main/resources/mapper/calendarMapper.xml
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/resources/mybatis-config.xml
  istudy/src/main/webapp/WEB-INF/views/study/calendar/calendarList.jsp
  istudy/src/main/webapp/lib/main.js
  istudy/src/main/webapp/upload/qna/favicon.png
  istudy/src/main/webapp/upload/qna/htm_2013102810154430103011 (1).jpg
  istudy/src/main/webapp/upload/qna/htm_2013102810154430103011.jpg
  istudy/src/main/webapp/upload/qna/lamp.png
  istudy/src/main/webapp/upload/qna/lamp02.png
  istudy/src/main/webapp/upload/qna/like_1_sky.png
Labels: enhancement

#65 Board공통 - 조회수 올리기 기능
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/BoardDAO.java
  istudy/src/main/java/com/hot6/project/service/BoardService.java
  istudy/src/main/java/com/hot6/project/service/BoardServiceImpl.java
  istudy/src/main/resources/mapper/boardMapper.xml
  istudy/src/main/resources/mapper/qnaMapper.xml
Labels: enhancement

#68 [FEAT] Toast UI Editor 적용(마크다운 가능)
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/BoardDAO.java
  istudy/src/main/java/com/hot6/project/dao/QnaDAO.java
  istudy/src/main/java/com/hot6/project/service/BoardService.java
  istudy/src/main/java/com/hot6/project/service/BoardServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/QnaService.java
  istudy/src/main/java/com/hot6/project/service/QnaServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/BoardVO.java
  istudy/src/main/resources/mapper/boardMapper.xml
  istudy/src/main/resources/mapper/qnaMapper.xml
  istudy/src/main/webapp/WEB-INF/views/qna/qnaEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaList.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaWrite.jsp
  istudy/src/main/webapp/css/qna/qnaEdit.css
  istudy/src/main/webapp/css/qna/qnaView.css
  istudy/src/main/webapp/css/qna/qnaWrite.css
  istudy/src/main/webapp/upload/qna/lamp.png
  istudy/src/main/webapp/upload/qna/lamp02.png
  istudy/src/main/webapp/upload/qna/like_1_sky.png
Labels: enhancement

#69 레벨 아이콘 표시
  istudy/src/main/java/com/hot6/project/vo/BoardVO.java
  istudy/src/main/resources/mapper/boardMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/css/home/home.css
  istudy/src/main/webapp/css/qna/qnaView.css
Labels: enhancement

#70 회원가입, 수정, 마이페이지 프로필 이미지 수정
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/src/main/java/com/hot6/project/controller/AdminUserController.java
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/AdminUserDAO.java
  istudy/src/main/java/com/hot6/project/service/AdminUserService.java
  istudy/src/main/java/com/hot6/project/service/AdminUserServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/UserVO.java
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userForm.jsp
  istudy/src/main/webapp/css/home/home.css
  istudy/src/main/webapp/css/users/userEdit.css
  istudy/src/main/webapp/css/users/userForm.css
  istudy/src/main/webapp/js/users/userEdit.js
  istudy/src/main/webapp/js/users/userForm.js
Labels: enhancement

#71 마이페이지 및 회원 관리자 페이지 수정 완료
  istudy/bin/main/com/hot6/project/vo/UserVO.class
  istudy/src/main/java/com/hot6/project/controller/AdminUserController.java
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/dao/AdminUserDAO.java
  istudy/src/main/java/com/hot6/project/dao/MypageDAO.java
  istudy/src/main/java/com/hot6/project/service/AdminUserService.java
  istudy/src/main/java/com/hot6/project/service/AdminUserServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/MypageService.java
  istudy/src/main/java/com/hot6/project/service/MypageServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/UserVO.java
  istudy/src/main/resources/mapper/adminUserMapper.xml
  istudy/src/main/resources/mapper/mypageMapper.xml
  istudy/src/main/webapp/WEB-INF/views/admin/adminUsers.jsp
  istudy/src/main/webapp/WEB-INF/views/admin/users.jsp
  istudy/src/main/webapp/WEB-INF/views/users/idSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewComment.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/users/pwdSearch.jsp
  istudy/src/main/webapp/css/admin/adminUsers.css
  istudy/src/main/webapp/css/mypage/study.css
  istudy/src/main/webapp/css/mypage/viewComment.css
  istudy/src/main/webapp/css/mypage/viewWrite.css
  istudy/src/main/webapp/css/users/loginIdPassword.css
  istudy/src/main/webapp/js/admin/adminUsers.js
  istudy/src/main/webapp/js/mypage/mypage.js
  istudy/src/main/webapp/js/users/idSearch.js
  istudy/src/main/webapp/js/users/login.js
  istudy/src/main/webapp/js/users/pwdSearch.js
Labels: enhancement

#72 회원 관리자 페이지 redirect 수정
  istudy/src/main/java/com/hot6/project/controller/AdminUserController.java
  istudy/src/main/webapp/WEB-INF/views/admin/adminUsers.jsp
Labels: enhancement

#75 Feat/web rtc hyeyoung
  istudy/src/main/java/com/hot6/project/controller/AdminNoticeController.java
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/webapp/WEB-INF/views/qna/qnaEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaWrite.jsp
  istudy/src/main/webapp/ckUpload/qna/29b2ea23-3bc4-4e4f-b038-dc3977563653_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/qna/302ffdfc-e040-4b1d-9f5c-bc9664763632_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/qna/7639fa82-f92c-4472-89a3-7fc28f6aa100_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/qna/7aecb2ce-db14-4d4b-847c-562470442b4f_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/qna/a4196f3f-6f2c-4206-85bf-fcf1eec04680_htm_2013102810154430103011.jpg
  istudy/src/main/webapp/ckUpload/qna/c8284492-e298-4793-bbd9-c06016f3a0ac_캡처_2022_05_14_02_34_50_938.png
Labels: enhancement

#76 ckeditor 적용
  istudy/src/main/java/com/hot6/project/ServerConfigurer.java
  istudy/src/main/java/com/hot6/project/controller/AdminNoticeController.java
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/webapp/WEB-INF/views/admin/notice/adminNoticeEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/admin/notice/adminNoticeWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/notice/noticeList.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaEdit.jsp
  istudy/src/main/webapp/ckUpload/11d69d93-d440-4c9c-9b8b-462d46f8991d_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/11f53ee1-ebbb-48d8-941c-136b04a03499_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/2af9a868-90a6-4591-84f9-7e126cd3ace7_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/51486ab5-a2e9-4566-a047-626efa49bb40_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/5dddf8cf-a152-4463-8183-d9afc1e8c23b_htm_2013102810154430103011.jpg
  istudy/src/main/webapp/ckUpload/5eb8ba20-3ab0-48e7-bf6d-b2c4dab7fb0c_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/b10bc84d-7d0c-42c3-8e19-454aad14b578_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/bd39158f-ee5f-466b-92f5-78e508429c91_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/ckUpload/c6acaacb-c9c6-48b8-bb2f-3239a523d659_htm_2013102810154430103011.jpg
  istudy/src/main/webapp/ckUpload/de75ff5f-ceb4-46ae-a05a-a7784b2795f9_htm_2013102810154430103011.jpg
  istudy/src/main/webapp/ckUpload/fd6f0739-8d6a-4425-a0ff-3a6e9ebc99ae_캡처_2022_05_14_02_34_50_938.png
  istudy/src/main/webapp/js/notice/noticeList.js
Labels: enhancement

#77 [FEAT] webSocket 공유 캔버스 기능 완성
  istudy/src/main/java/com/hot6/project/controller/WebSocketController.java
  istudy/src/main/java/com/hot6/project/handler/WhiteBoardSocketHandler.java
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/canvas.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studyPage.jsp
  istudy/src/main/webapp/ckUpload/18c22b9b-4224-4ae3-8815-d8c9b12cd18f_캡처_2022_05_14_02_34_50_938.png
Labels: enhancement

#79 글,댓글,좋아요,채택 시 점수 올리고내리는 기능 / 공지사항 조회수 올리기
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/NoticeController.java
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/BoardDAO.java
  istudy/src/main/java/com/hot6/project/service/BoardService.java
  istudy/src/main/java/com/hot6/project/service/BoardServiceImpl.java
  istudy/src/main/resources/mapper/boardMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
Labels: enhancement

#81 데이터 랩 페이지 구현
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/bin/main/com/hot6/project/vo/UserVO.class
  istudy/src/main/java/com/hot6/project/controller/AdminDataController.java
  istudy/src/main/java/com/hot6/project/dao/AdminDataDAO.java
  istudy/src/main/java/com/hot6/project/service/AdminDataService.java
  istudy/src/main/java/com/hot6/project/service/AdminDataServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/java/com/hot6/project/vo/UserVO.java
  istudy/src/main/resources/mapper/adminDataMapper.xml
  istudy/src/main/webapp/WEB-INF/views/admin/adminData.jsp
  istudy/src/main/webapp/WEB-INF/views/admin/adminUsers.jsp
  istudy/src/main/webapp/css/admin/adminData.css
  istudy/src/main/webapp/css/mypage/study.css
  istudy/src/main/webapp/css/mypage/viewComment.css
  istudy/src/main/webapp/css/mypage/viewWrite.css
Labels: enhancement

#82 마이페이지 팝업 추가
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewComment.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
Labels: enhancement

#83 Feat/studyinfo jayoung
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/src/main/java/com/hot6/project/controller/StudyDetailController.java
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDAO.java
  istudy/src/main/java/com/hot6/project/dao/StudyDetailDAO.java
  istudy/src/main/java/com/hot6/project/dao/StudyInfoDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailService.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoService.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/PagingVO.java
  istudy/src/main/java/com/hot6/project/vo/StudyInfoVO.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyDetail.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/css/studyhome/studydetail.css
  istudy/src/main/webapp/css/studyhome/studyhome.css
  istudy/src/main/webapp/images/study_info/study_default.jpg
  istudy/src/main/webapp/js/studyhome/studyhome.js
Labels: enhancement

#84 Feat/study info hyeyoung
  DB/DB 초기값.sql
  DB/IsTudy_project model.mwb
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/MypageDAO.java
  istudy/src/main/java/com/hot6/project/service/MypageService.java
  istudy/src/main/java/com/hot6/project/service/MypageServiceImpl.java
  istudy/src/main/resources/mapper/mypageMapper.xml
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userEdit.jsp
  istudy/src/main/webapp/css/mypage/study.css
  istudy/src/main/webapp/js/mypage/mypage.js
Labels: enhancement

#85 Q&A 마무리작업
  istudy/src/main/java/com/hot6/project/controller/AdminNoticeController.java
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/NoticeController.java
  istudy/src/main/java/com/hot6/project/controller/QnaController.java
  istudy/src/main/java/com/hot6/project/dao/QnaDAO.java
  istudy/src/main/java/com/hot6/project/service/QnaService.java
  istudy/src/main/java/com/hot6/project/service/QnaServiceImpl.java
  istudy/src/main/resources/mapper/qnaMapper.xml
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/notice/adminNoticeEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/notice/adminNoticeWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/notice/noticeList.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaList.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaWrite.jsp
  istudy/src/main/webapp/ckUpload/2ba5ec35-ebba-4036-8669-5e04b14c7589_coding_interest_group_2021_v2+(1).png
  istudy/src/main/webapp/ckUpload/5201e93a-8605-430e-9e8d-2159b5a5b38d_rank2.png
  istudy/src/main/webapp/ckUpload/5dc3bb91-0a32-4964-a34f-83f5f6cc5e14_IMG_0006.JPG
  istudy/src/main/webapp/ckUpload/5dd209a2-2f94-4e65-aaab-a4ed6813bb33_main2.png
  istudy/src/main/webapp/ckUpload/9d84bf04-1cbd-480f-960d-671d8c8f4e63_Coding-Class-for-Kids.jpg
  istudy/src/main/webapp/ckUpload/a19bba65-0c83-4934-a3e3-6fac7cd77d2d_IMG_0006.JPG
  istudy/src/main/webapp/ckUpload/de825e20-35b7-42a1-958c-5c66af1d0529_9-99450_high-quality-web-icons-clipart-free-computer-students.png
  istudy/src/main/webapp/ckUpload/notice/293541e5-e894-4c24-afe4-881865cd4cdd_20210511_143403.jpg
  istudy/src/main/webapp/ckUpload/notice/3a68399a-7155-47fa-9672-e2df3191ff46_20210511_123637.jpg
  istudy/src/main/webapp/ckUpload/notice/473cff05-1479-42c6-961b-de05d4592281_coding_interest_group_2021_v2+(1).png
  istudy/src/main/webapp/ckUpload/notice/5456ff8f-aea1-4b4b-ae27-7cc1c73285db_레이어 0.png
  istudy/src/main/webapp/ckUpload/notice/78414e82-1611-4459-adc3-84490420cd0b_20210511_143706.jpg
  istudy/src/main/webapp/ckUpload/notice/95a03912-b9e6-4415-b43f-6ff08604f5e1_레이어 0.png
  istudy/src/main/webapp/ckUpload/notice/99f9330d-840b-4789-91db-ba0f2a750edb_20210511_140856.jpg
  istudy/src/main/webapp/ckUpload/notice/9cf335ce-b732-47b4-b901-c81ad21251fa_20210511_143409.jpg
  istudy/src/main/webapp/ckUpload/notice0e8a3c29-531a-4951-9200-c5dc4370445d_FAdLK6pVQAkPUC1.png
  istudy/src/main/webapp/ckUpload/notice36921cfe-aa0f-410d-98bd-2c89bf0dae24_main3.png
  istudy/src/main/webapp/ckUpload/noticea161e020-d1de-449b-8017-24cc4cacd40c_rank3.png
  istudy/src/main/webapp/css/adminData.css
  istudy/src/main/webapp/css/adminUsers.css
  istudy/src/main/webapp/css/home/home.css
  istudy/src/main/webapp/css/inc/top.css
  istudy/src/main/webapp/css/notice/adminNoticeEdit.css
  istudy/src/main/webapp/css/notice/adminNoticeWrite.css
  istudy/src/main/webapp/css/notice/noticeList.css
  istudy/src/main/webapp/css/qna/qnaEdit.css
  istudy/src/main/webapp/css/qna/qnaList.css
  istudy/src/main/webapp/css/qna/qnaView.css
  istudy/src/main/webapp/css/qna/qnaWrite.css
  istudy/src/main/webapp/js/admin/Notice/adminNotice.js
  istudy/src/main/webapp/js/notice/noticeList.js
Labels: enhancement

#86 Feat/study room hyeyoung
  istudy/bin/main/com/hot6/project/HomeController.class
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/src/main/java/com/hot6/project/HomeController.java
  istudy/src/main/java/com/hot6/project/controller/CalendarController.java
  istudy/src/main/java/com/hot6/project/controller/StudyRoomController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/StudyRoomDAO.java
  istudy/src/main/java/com/hot6/project/interceptor/LoginInterceptor.java
  istudy/src/main/java/com/hot6/project/service/StudyRoomService.java
  istudy/src/main/java/com/hot6/project/service/StudyRoomServiceImpl.java
  istudy/src/main/webapp/WEB-INF/views/study/calendar/calendarList.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyRoom.jsp
  istudy/src/main/webapp/css/study/studyCalendar.css
  istudy/src/main/webapp/images/study_room/room01.png
  istudy/src/main/webapp/images/study_room/room02.png
  istudy/src/main/webapp/images/study_room/screen01.png
Labels: enhancement

#87 화면공유 부분 CSS완료
  istudy/src/main/java/com/hot6/project/controller/NoticeController.java
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/chatPage.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/screenShare.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studyBottom.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studyPageChat.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studyPageMatesList.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studySidebar.jsp
  istudy/src/main/webapp/css/inc/top.css
  istudy/src/main/webapp/css/notice/noticeEdit.css
  istudy/src/main/webapp/css/notice/noticeWrite.css
  istudy/src/main/webapp/css/qna/qnaList.css
  istudy/src/main/webapp/css/qna/qnaView.css
  istudy/src/main/webapp/css/study/studyBottom.css
  istudy/src/main/webapp/css/study/studySidebar.css
Labels: enhancement

#88 Feat/study room hyeyoung
  istudy/src/main/java/com/hot6/project/controller/StudyRoomController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDetailDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailService.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailServiceImpl.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyRoom.jsp
Labels: enhancement

#89 스터디 등록 페이지 전체 수정.
  istudy/src/main/java/com/hot6/project/controller/StudyBoardController.java
  istudy/src/main/java/com/hot6/project/controller/StudyRegisterController.java
  istudy/src/main/java/com/hot6/project/dao/StudyBoardDAO.java
  istudy/src/main/java/com/hot6/project/dao/StudyRegisterDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyBoardService.java
  istudy/src/main/java/com/hot6/project/service/StudyBoardServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyRegisterService.java
  istudy/src/main/java/com/hot6/project/service/StudyRegisterServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/StudyRegisterVO.java
  istudy/src/main/resources/mapper/studyboardMapper.xml
  istudy/src/main/resources/mapper/studyregisterMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardList.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardView.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/registerform.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_0.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_1.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_2.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_3.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/studyregister_4.jsp
  istudy/src/main/webapp/css/studyboard/studyboard.css
  istudy/src/main/webapp/css/studyregister/studyregister.css
  istudy/src/main/webapp/images/studyregister/plus.png
  istudy/src/main/webapp/js/studyboard/bulletinBoard.js
  istudy/src/main/webapp/js/studyregister/currentDate.js
  istudy/src/main/webapp/js/studyregister/dragDrop.js
  istudy/src/main/webapp/js/studyregister/studyregisterForm.js
  istudy/src/main/webapp/js/studyregister/tagSelect.js
Labels: bug

#90 [FEAT] 스터디 정보, 상세
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/src/main/java/com/hot6/project/controller/StudyDetailController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDetailDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailService.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoService.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyDetail.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/css/studyhome/studydetail.css
  istudy/src/main/webapp/css/studyhome/studyhome.css
  istudy/src/main/webapp/images/study_info/profile_default.png
Labels: enhancement

#91 관리자 신고관리 페이지 구현
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/com/hot6/project/dao/UserDAO.class
  istudy/bin/main/com/hot6/project/service/UserService.class
  istudy/bin/main/com/hot6/project/service/UserServiceImpl.class
  istudy/bin/main/com/hot6/project/vo/UserVO.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/src/main/java/com/hot6/project/controller/AdminUserController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/java/com/hot6/project/dao/AdminUserDAO.java
  istudy/src/main/java/com/hot6/project/dao/UserDAO.java
  istudy/src/main/java/com/hot6/project/service/AdminUserService.java
  istudy/src/main/java/com/hot6/project/service/AdminUserServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/UserService.java
  istudy/src/main/java/com/hot6/project/service/UserServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/PagingVO.java
  istudy/src/main/java/com/hot6/project/vo/UserVO.java
  istudy/src/main/resources/mapper/adminUserMapper.xml
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/admin/adminData.jsp
  istudy/src/main/webapp/WEB-INF/views/admin/adminUsers.jsp
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewComment.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userForm.jsp
  istudy/src/main/webapp/css/admin/adminData.css
  istudy/src/main/webapp/css/admin/adminUsers.css
  istudy/src/main/webapp/css/mypage/study.css
  istudy/src/main/webapp/css/mypage/viewComment.css
  istudy/src/main/webapp/css/users/userEdit.css
  istudy/src/main/webapp/css/users/userForm.css
  istudy/src/main/webapp/js/users/userForm.js
Labels: enhancement

#92 AdminUserVO 추가
  istudy/src/main/java/com/hot6/project/vo/AdminUserVO.java
Labels: enhancement

#93 Feat/study room hyeyoung
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/bin/main/mapper/studyMapper.xml
  istudy/src/main/java/com/hot6/project/controller/StudyRoomController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDetailDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailService.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/studyMapper.xml
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyRoom.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studyBottom.jsp
  istudy/src/main/webapp/css/studyhome/studyRoom.css
Labels: enhancement

#94 adminReport jsp, css, js 추가
  istudy/src/main/webapp/WEB-INF/views/admin/adminReport.jsp
  istudy/src/main/webapp/css/admin/adminReport.css
  istudy/src/main/webapp/js/admin/adminReport.js
Labels: enhancement

#95 마이스터디, 데이터 랩 수정
  istudy/src/main/java/com/hot6/project/controller/AdminDataController.java
  istudy/src/main/resources/mapper/adminDataMapper.xml
  istudy/src/main/webapp/WEB-INF/views/admin/adminData.jsp
  istudy/src/main/webapp/WEB-INF/views/admin/adminUsers.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/study.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewComment.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
  istudy/src/main/webapp/css/mypage/study.css
Labels: enhancement

#97 css url 수정
  istudy/src/main/java/com/hot6/project/controller/StudyRegisterController.java
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/registerform.jsp
  istudy/src/main/webapp/WEB-INF/views/users/pwdSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userForm.jsp
Labels: bug

#98 study 홈 페이징
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/java/com/hot6/project/dao/StudyInfoDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoService.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/PagingVO.java
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/notice/noticeEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/notice/noticeList.jsp
  istudy/src/main/webapp/WEB-INF/views/notice/noticeWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/canvas.jsp
  istudy/src/main/webapp/css/inc/top.css
  istudy/src/main/webapp/css/notice/noticeList.css
  istudy/src/main/webapp/css/notice/noticeWrite.css
  istudy/src/main/webapp/css/qna/qnaEdit.css
  istudy/src/main/webapp/css/qna/qnaList.css
  istudy/src/main/webapp/css/qna/qnaView.css
  istudy/src/main/webapp/css/qna/qnaWrite.css
Labels: enhancement

#99 스터디 게시판, 스터디 상세페이지
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/StudyBoardController.java
  istudy/src/main/java/com/hot6/project/controller/StudyRegisterController.java
  istudy/src/main/java/com/hot6/project/controller/StudyRoomController.java
  istudy/src/main/java/com/hot6/project/dao/StudyBoardDAO.java
  istudy/src/main/java/com/hot6/project/dao/StudyRegisterDAO.java
  istudy/src/main/java/com/hot6/project/interceptor/ServerConfigure.java
  istudy/src/main/java/com/hot6/project/service/StudyBoardService.java
  istudy/src/main/java/com/hot6/project/service/StudyBoardServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyRegisterService.java
  istudy/src/main/java/com/hot6/project/service/StudyRegisterServiceImpl.java
  istudy/src/main/resources/mapper/studyboardMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardList.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardView.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyBoard/studyBoardWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyRoom.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyboard/studyboardEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyboard/studyboardList.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyboard/studyboardView.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyboard/studyboardWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/registerform.jsp
  istudy/src/main/webapp/css/studyboard/studyboard.css
  istudy/src/main/webapp/css/studyboard/studyboardEdit.css
  istudy/src/main/webapp/css/studyboard/studyboardList.css
  istudy/src/main/webapp/css/studyboard/studyboardView.css
  istudy/src/main/webapp/css/studyboard/studyboardWrite.css
  istudy/src/main/webapp/css/studyhome/studyRoom.css
  istudy/src/main/webapp/css/studyregister/studyregister.css
Labels: enhancement

#101 Feat/study room hyeyoung
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/src/main/java/com/hot6/project/controller/BoardController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/webapp/WEB-INF/views/qna/qnaWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyboard/studyboardView.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studyBottom.jsp
  istudy/src/main/webapp/WEB-INF/web.xml
  istudy/src/main/webapp/ckUpload/2e0c59e2-a066-41da-aa7b-970e2d1a62a4_person_1.png
  istudy/src/main/webapp/ckUpload/72d67065-f2e1-47ac-925a-29489406519a_person_1.png
  istudy/src/main/webapp/images/study_info/person_0.png
  istudy/src/main/webapp/images/study_info/person_1.png
Labels: enhancement

#102 메인 페이지 멘토, 회원 사진 수정
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/bin/main/mapper/userMapper.xml
  istudy/src/main/java/com/hot6/project/controller/MypageController.java
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/resources/mapper/userMapper.xml
  istudy/src/main/webapp/WEB-INF/views/admin/adminUsers.jsp
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/WEB-INF/views/users/idSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/login.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewComment.jsp
  istudy/src/main/webapp/WEB-INF/views/users/mypage/viewWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/users/pwdSearch.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userForm.jsp
  istudy/src/main/webapp/css/admin/adminReport.css
  istudy/src/main/webapp/css/admin/adminUsers.css
  istudy/src/main/webapp/css/home/home.css
  istudy/src/main/webapp/css/mypage/study.css
  istudy/src/main/webapp/css/mypage/viewComment.css
  istudy/src/main/webapp/css/mypage/viewWrite.css
  istudy/src/main/webapp/css/users/loginIdPassword.css
  istudy/src/main/webapp/css/users/userEdit.css
  istudy/src/main/webapp/css/users/userForm.css
  istudy/src/main/webapp/upload/user/food2_choco0000.jpg
  istudy/src/main/webapp/upload/user/food5_choco0000.jpg
  istudy/src/main/webapp/upload/user/light_food0000.jpg
  istudy/src/main/webapp/upload/user/고수_gggg0000.jpg
  istudy/src/main/webapp/upload/user/멘토1_ffff0000.jpg
  istudy/src/main/webapp/upload/user/멘토2_eeee0000.jpg
  istudy/src/main/webapp/upload/user/박명수_jjjj0000.jpg
  istudy/src/main/webapp/upload/user/타블로_hhhh0000.jpg
Labels: enhancement

#103 신고관리, 마이페이지 기능 수정
  istudy/bin/main/com/hot6/project/controller/UserController.class
Labels: enhancement

#104 Feat/study room hyeyoung
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/qna/qnaWrite.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
Labels: enhancement

#105 스터디 정보/상세 페이지 추가
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/src/main/java/com/hot6/project/controller/StudyDetailController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDetailDAO.java
  istudy/src/main/java/com/hot6/project/dao/StudyInfoDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailService.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailServiceImpl.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoService.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyDetail.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/css/studyhome/studydetail.css
  istudy/src/main/webapp/css/studyhome/studyhome.css
  istudy/src/main/webapp/js/studyhome/studydetail.js
  istudy/src/main/webapp/js/studyhome/studyhome.js
Labels: enhancement

#106 등록 기능 버그 수정
  istudy/bin/main/com/hot6/project/vo/StudyVO.class
  istudy/src/main/java/com/hot6/project/controller/StudyRegisterController.java
  istudy/src/main/java/com/hot6/project/vo/StudyVO.java
  istudy/src/main/resources/mapper/studyregisterMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/WEB-INF/views/studyregister/registerform.jsp
Labels: bug

#107 관리자페이지 프로필 이미지 수정, 회원 탈퇴 수정, 스터디/QnA 게시판 신고하기 프론트 작업
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/src/main/java/com/hot6/project/controller/AdminUserController.java
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/webapp/WEB-INF/views/admin/adminReport.jsp
  istudy/src/main/webapp/WEB-INF/views/admin/adminUsers.jsp
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyboard/studyboardView.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userEdit.jsp
  istudy/src/main/webapp/WEB-INF/views/users/userForm.jsp
  istudy/src/main/webapp/css/admin/adminData.css
  istudy/src/main/webapp/css/admin/adminReport.css
  istudy/src/main/webapp/css/admin/adminUsers.css
  istudy/src/main/webapp/css/qna/qnaView.css
  istudy/src/main/webapp/css/studyboard/studyboardView.css
  istudy/src/main/webapp/css/users/userEdit.css
  istudy/src/main/webapp/css/users/userForm.css
  istudy/src/main/webapp/js/admin/adminReport.js
  istudy/src/main/webapp/js/users/userEdit.js
  istudy/src/main/webapp/js/users/userForm.js
Labels: enhancement

#108 studyHome CSS 완료
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/webapp/WEB-INF/views/inc/top.jspf
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/WEB-INF/views/study/webSocket/studyBottom.jsp
  istudy/src/main/webapp/ckUpload/42497a52-c762-4669-930d-0ded32d984b1_SE-574fc58d-abb1-442e-a19b-317921fb30ad.jpg
  istudy/src/main/webapp/ckUpload/c5aa3155-ded0-4609-b967-877c67ba98ff_SE-574fc58d-abb1-442e-a19b-317921fb30ad.jpg
  istudy/src/main/webapp/ckUpload/cfaa44e5-22fb-4bf3-a100-4b1f415fb3e7_images.jpg
  istudy/src/main/webapp/css/studyhome/studyhome.css
Labels: enhancement

#112 스터디 상세 페이지 신청 여부 기능
  istudy/src/main/java/com/hot6/project/controller/StudyDetailController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDetailDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailService.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailServiceImpl.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyDetail.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
  istudy/src/main/webapp/css/studyhome/studydetail.css
  istudy/src/main/webapp/css/studyhome/studyhome.css
  istudy/src/main/webapp/images/study_info/agree.png
  istudy/src/main/webapp/images/study_info/check.png
  istudy/src/main/webapp/js/studyhome/studydetail.js
Labels: enhancement

#113 Feat/study room hyeyoung
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/java/com/hot6/project/dao/StudyInfoDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoService.java
  istudy/src/main/java/com/hot6/project/service/StudyInfoServiceImpl.java
  istudy/src/main/java/com/hot6/project/vo/PagingVO.java
  istudy/src/main/resources/mapper/studyinfoMapper.xml
Labels: enhancement

#114 Feat/study room hyeyoung
  istudy/src/main/java/com/hot6/project/controller/StudyDetailController.java
  istudy/src/main/java/com/hot6/project/dao/StudyDetailDAO.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailService.java
  istudy/src/main/java/com/hot6/project/service/StudyDetailServiceImpl.java
  istudy/src/main/resources/mapper/studydetailMapper.xml
  istudy/src/main/webapp/WEB-INF/views/study/studyDetail.jsp
Labels: enhancement

#118 top, login css 수정
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/webapp/css/inc/top.css
  istudy/src/main/webapp/css/users/loginIdPassword.css
Labels: enhancement

#119 Feat/study room hyeyoung
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/src/main/java/com/hot6/project/controller/UserController.java
  istudy/src/main/resources/mapper/studyinfoMapper.xml
  istudy/src/main/webapp/WEB-INF/views/home.jsp
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
Labels: enhancement

#120 Feat/study room hyeyoung
  istudy/bin/main/com/hot6/project/controller/UserController.class
  istudy/src/main/webapp/WEB-INF/views/study/studyDetail.jsp
Labels: bug

#121 관리자 페이지 CSS 수정
  istudy/src/main/java/com/hot6/project/controller/AdminUserController.java
  istudy/src/main/webapp/css/admin/adminData.css
  istudy/src/main/webapp/css/admin/adminReport.css
  istudy/src/main/webapp/css/admin/adminUsers.css
  istudy/src/main/webapp/css/inc/top.css
Labels: enhancement

#122 마이페이지 스터디 mapper 수정
  istudy/src/main/resources/mapper/mypageMapper.xml
  istudy/src/main/webapp/WEB-INF/views/qna/qnaView.jsp
  istudy/src/main/webapp/upload/user/사용자1_remy0000.jpg
Labels: enhancement

#123 Feat/study room hyeyoung
  istudy/src/main/java/com/hot6/project/controller/StudyInfoController.java
  istudy/src/main/webapp/WEB-INF/views/study/studyHome.jsp
Labels: enhancement

#127 [FEAT] 스터디룸 게시판 ul 크기 수정
  istudy/src/main/webapp/css/studyboard/studyboardList.css
Labels: bug

#128 [DB] 데이터베이스 모델링 최종
  DB/DB 초기값.sql
  DB/IsTudy_project model.mwb
Labels: enhancement
